const jwt = require('jsonwebtoken');
const Login = require('../models/network');
const Keys = require('../config/keys');

module.exports = {
    /*
        Will be translated to get("/people") (first level is generated by controller name)
    */
    // userAuth: function (req, res, next) {
    //     // return true;
    //     // call model here
    //     data = true;
    //     if (data) {
    //         return next();
    //     }
    //     return res.status(301).render('login');
    // },

    /*
        Will be translated to get("/people/:userName/friend-requests") (non parameter parts that use camelCase will be separated by hyphens in the url)
    */
    userLogin: async(req, res, next) => {
        // console.log('Post for login controller');

        const username = req.body.username;
        const password = req.body.password;
        // console.log(username);
        // console.log(password);

        // call model here
        try {
            let user = await Login.getUserByUsername(username);
            if (!user.success) {
                return res.json({
                    success: false,
                    msg: 'User not found'
                });
            } else {
                user = user.data
            }

            let pass = await Login.comparePassword(password, user.password);
            // console.log('pass ', pass);
            if (!pass.success) {
                return res.json({
                    success: false,
                    msg: 'Password not match'
                });
            }else{
                delete user.password;   //  its not working now
                user.password = '';
            }
            jwt.sign({ user }, Keys.usersession.secretKey, { expiresIn: '3h' }, (err, token) => {
                if (err) {
                    res.redirect('/login'); // redirect to login page if token not found
                } else {
                    res.cookie('authorization', token, {
                        maxAge: 3 * 60 * 60 * 1000, // 3 hours
                        // httpOnly: true, // http only, prevents JavaScript cookie access
                        // secure: true // cookie must be sent over https / ssl
                    });
                    return res.redirect('dashboard'); // Continue execution
                }
            });
        } catch (e) {
            next(e);
        }

    },

    // FORMAT OF TOKEN
    // Authorization: Bearer <access_token>
    // Verify Token
    verifyToken: function (req, res, next) {
        // console.log('verify Token');
        // const bearerHeader = req.headers['authorization'];    // Get auth header value
        const bearerHeader = req.cookies['authorization']; // Get auth header value
        if (typeof bearerHeader !== 'undefined') { // Check if bearer is undefined
            // req.token = bearerHeader.split(' ')[1];
            req.token = bearerHeader;
            jwt.verify(req.token, Keys.usersession.secretKey, (err, authData) => {
                if (err) {
                    res.redirect('/login'); // redirect to login page if token not found
                } else {
                    // ############################################################
                    //            this variable is global variable 
                                    userHeader = authData.user;
                    // ############################################################
                    // console.log('userHeader', userHeader);
                    next(); // Continue execution
                }
            });
        } else {
            res.redirect('/login'); // redirect to home page if token not found
        }

    }
}