var login = require('../models/login');

module.exports = {
    /*
        Will be translated to get("/people") (first level is generated by controller name)
    */
    userAuth : function(req, res, next) {
        // return true;
        // call model here
        data = true;
        if (data) {
			return next();
		}
		return res.status(301).render('login');
    },

    /*
        Will be translated to get("/people/:userName/friend-requests") (non parameter parts that use camelCase will be separated by hyphens in the url)
    */
    userLogin : function(req, res, next) {
    	console.log('Post for login controller');
        // call model here
        data = false;
        if (data) {
			return res.redirect('dashboard');
		}
		return res.redirect('login');
    }
}
