var users = require('../models/users');

module.exports = {
    /*
        Will be translated to get("/people") (first level is generated by controller name)
    */
    userAuth : function(req, res, next) {
        // return true;
        // call model here
        data = true;
        if (data) {
			return next();
		}
		return res.status(301).render('login');
    },

    /*
        Will be translated to get("/people/:userName/friend-requests") (non parameter parts that use camelCase will be separated by hyphens in the url)
    */
    userLogin : function(req, res, next) {
    	console.log('Post for login controller');
        // call model here
        data = false;
        if (data) {
			return res.redirect('dashboard');
		}
		return res.redirect('login');
    },

    userslist : async (req, res, next) => {
            console.log('controller userslist');
        try {
            let data = await users.getUserList(req)
            if(!data) {
            return res.json({success: false, msg: 'Users not found'});
            }
            // data.toString().replace('"_id"','"id"');
            res.json(data);
        } catch(e) {
            next(e);
        }
    }
}    